Replacing instances of "moxie" with "nolte"
moxie-leean/landing pull request #11
Opened 2016-11-29 16:59 UTC by btchae

Let me know if I missed anything.

2016-12-06 03:21 UTC, mitogh requested changes

2016-12-06 03:21 UTC, mitogh commented on index.html
> +      <img src="src/images/nolte-footer.png" alt="" class="footer_brand__media">
Did you renamed the files as well?

2016-12-09 19:06 UTC, btchae commented on index.html
> +      <img src="src/images/nolte-footer.png" alt="" class="footer_brand__media">
I did not. They have the moxie logo so I think there would have to be new files.

2016-12-20 17:12 UTC, mitogh commented on index.html
> +      <img src="src/images/nolte-footer.png" alt="" class="footer_brand__media">
Okay can you add those then?

Thanks.

2016-12-23 17:53 UTC, btchae commented on index.html
> +      <img src="src/images/nolte-footer.png" alt="" class="footer_brand__media">
I removed moxie-footer.png with nolte-footer.png

2016-12-23 17:56 UTC, mitogh approved these changes

2016-12-23 17:56 UTC, merged